namespace Slang.CodeAnalysis.Syntax
{
    // Lists both tokens emitted by the lexer and non-terminal nodes generated by the parser
    public enum SyntaxKind : ushort
    {
        // -- Terminals --
        EofToken,
        InvalidToken,
        // Operators
        LeftParenToken,     // (
        RightParenToken,    // )
        LeftBraceToken,     // {
        RightBraceToken,    // }
        CommaToken,         // ,
        ColonToken,         // :
        SemicolonToken,     // ;
        DotToken,           // .
        PlusToken,          // +
        MinusToken,         // -
        StarToken,          // *
        SlashToken,         // /
        BangToken,          // !
        BangEqualToken,     // !=
        EqualToken,         // =
        EqualEqualToken,    // ==
        GreaterToken,       // >
        GreaterEqualToken,  // >=
        LessToken,          // <
        LessEqualToken,     // <=

        // Literals
        IdentifierToken,
        StringLiteralToken,
        IntegerLiteralToken,
        FloatLiteralToken,

        // Trivia
        CommentToken,
        DoubleQuoteToken,
        WhitespaceToken,

        // Reserved Words
        GotoToken,
        FunToken,
        VarToken,
        IfToken,
        ElseToken,
        ReturnToken,
        TrueToken,
        FalseToken,

        // -- Non-terminals --

        Invalid,

        // Expressions
        UnaryExpression,
        BinaryExpression,
        GroupingExpression,
        LiteralExpression
    }
}
